// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateBatchCollaborators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateBatchCollaborators));
        
        string IMigrationMetadata.Id
        {
            get { return "201307260100352_CreateBatchCollaborators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
