// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateWebpages_Membership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateWebpages_Membership));
        
        string IMigrationMetadata.Id
        {
            get { return "201306102336151_CreateWebpages_Membership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
