// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fissomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fissomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201307282355130_fis-something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
