// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Recipe_Content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recipe_Content));
        
        string IMigrationMetadata.Id
        {
            get { return "201307282237058_Recipe_Content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
