// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class displaylabels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(displaylabels));
        
        string IMigrationMetadata.Id
        {
            get { return "201307142009410_display-labels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
