// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixsomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixsomething));
        
        string IMigrationMetadata.Id
        {
            get { return "201307271504422_fix-something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
