// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewRecipeColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewRecipeColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201307290117266_New-Recipe-Columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
