// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class frienduser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(frienduser));
        
        string IMigrationMetadata.Id
        {
            get { return "201307300022159_friend-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
