// <auto-generated />
namespace BrewersBuddy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateBatchRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateBatchRating));
        
        string IMigrationMetadata.Id
        {
            get { return "201306091918176_CreateBatchRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
